version: '3'

services:
    flaskapp:
      build:
          context: app
      ports:
        - "3000"
    nginx:
        image: nginx:1.24.0
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - flaskapp
        ports:
          - "80:80"
