version: '3'

services:
    app:
      build:
          context: app
      ports:
        - "5000"
    nginx:
        image: nginx:1.24.0
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
          - "8000:80"
